[package]
name = "rust-csv-reader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fast-float = "0.2.0"
memchr = "2.7.1"
memmap = "0.7.0"
paste = "1.0.14"
